export const imageMap: { [key: string]: any } = {
  'Volkswagen-Golf/golf.png': require('@/assets/images/Car-images/Volkswagen-Golf/golf.png'),
  'Dacia-Logan/dacia.png': require('@/assets/images/Car-images/Dacia-Logan/dacia.png'),
  'Toyota-Corolla/corolla.png': require('@/assets/images/Car-images/Toyota-Corolla/corolla.png'),
  'BMW-X5/bmw.png': require('@/assets/images/Car-images/BMW-X5/bmw.png'),
  'Mercedess-E-Class/e-class.png': require('@/assets/images/Car-images/Mercedess-E-Class/e-class.png'),
  'Audi-A4/audi.jpg': require('@/assets/images/Car-images/Audi-A4/audi.jpg'),
  'Skoda-Octavia/skoda.png': require('@/assets/images/Car-images/Skoda-Octavia/skoda.png'),
  'Renault-Clio/reno.png': require('@/assets/images/Car-images/Renault-Clio/reno.png'),
  'Ford-Focus/ford.png': require('@/assets/images/Car-images/Ford-Focus/ford.png'),
  'Hyundai-Tucson/tucson.png': require('@/assets/images/Car-images/Hyundai-Tucson/tucson.png'),
  'Kia-Sportage/kia.png': require('@/assets/images/Car-images/Kia-Sportage/kia.png'),
  'Peugeot-3008/peugeot.png': require('@/assets/images/Car-images/Peugeot-3008/peugeot.png'),
  'Nissan-Qashqai/nissan.png': require('@/assets/images/Car-images/Nissan-Qashqai/nissan.png'),
  'Mazda-CX-5/mazda.png': require('@/assets/images/Car-images/Mazda-CX-5/mazda.png'),
  'Volvo-XC-60/volvo.png': require('@/assets/images/Car-images/Volvo-XC-60/volvo.png'),
  'Lexus-RX/lexus.png': require('@/assets/images/Car-images/Lexus-RX/lexus.png'),
  'Toyota-RAV4/rav4.png': require('@/assets/images/Car-images/Toyota-RAV4/rav4.png'),
  'Volkswagen-Passat/passat.png': require('@/assets/images/Car-images/Volkswagen-Passat/passat.png'),
  'BMW-3-Series/bmw-seria3.png': require('@/assets/images/Car-images/BMW-3-Series/bmw-seria3.png'),
};